
services:
  mysql:
    image: mysql:8.0
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: s1t1o1c1k
      MYSQL_DATABASE: stock_db
      MYSQL_USER: user
      MYSQL_PASSWORD: u8s
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stock-network

  app:
    build: .
    container_name: app_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: stock_db
      DB_USER: user
      DB_PASSWORD: u8s
#    command: [ "sh", "-c", "./wait-for-it.sh mysql:3306 -- java -jar app.jar" ]
    env_file:
      - src/main/resources/.env
    networks:
      - stock-network


volumes:
  mysql-data:

networks:
  stock-network:
    driver: bridge



